# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cat.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SegPoi(object):
    def setupUi(self, SegPoi):
        SegPoi.setObjectName("SegPoi")
        SegPoi.resize(479, 412)
        self.buttonBox = QtWidgets.QDialogButtonBox(SegPoi)
        self.buttonBox.setGeometry(QtCore.QRect(380, 380, 81, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(SegPoi)
        self.tabWidget.setGeometry(QtCore.QRect(20, 40, 441, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_POS = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_POS.setGeometry(QtCore.QRect(20, 100, 81, 17))
        self.checkBox_POS.setObjectName("checkBox_POS")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton_Segment = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Segment.setGeometry(QtCore.QRect(330, 100, 91, 21))
        self.pushButton_Segment.setObjectName("pushButton_Segment")
        self.myTextInput_2 = QtWidgets.QLineEdit(self.tab_3)
        self.myTextInput_2.setGeometry(QtCore.QRect(10, 70, 341, 21))
        self.myTextInput_2.setObjectName("myTextInput_2")
        self.toolButton = QtWidgets.QToolButton(self.tab_3)
        self.toolButton.setGeometry(QtCore.QRect(360, 30, 23, 18))
        self.toolButton.setObjectName("toolButton")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(10, 120, 151, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton_zht = QtWidgets.QRadioButton(self.frame)
        self.radioButton_zht.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.radioButton_zht.setChecked(True)
        self.radioButton_zht.setObjectName("radioButton_zht")
        self.radioButton_zhs = QtWidgets.QRadioButton(self.frame)
        self.radioButton_zhs.setGeometry(QtCore.QRect(10, 30, 181, 17))
        self.radioButton_zhs.setObjectName("radioButton_zhs")
        self.radioButton_en = QtWidgets.QRadioButton(self.frame)
        self.radioButton_en.setGeometry(QtCore.QRect(10, 50, 181, 17))
        self.radioButton_en.setObjectName("radioButton_en")
        self.myTextInput = QtWidgets.QLineEdit(self.tab_3)
        self.myTextInput.setGeometry(QtCore.QRect(11, 30, 341, 21))
        self.myTextInput.setObjectName("myTextInput")
        self.pushButton_Check = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Check.setGeometry(QtCore.QRect(330, 180, 91, 21))
        self.pushButton_Check.setObjectName("pushButton_Check")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(180, 99, 141, 101))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_tokLib_Stanford = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_tokLib_Stanford.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.radioButton_tokLib_Stanford.setChecked(True)
        self.radioButton_tokLib_Stanford.setObjectName("radioButton_tokLib_Stanford")
        self.radioButton_tokLib_ICTCLAS = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_tokLib_ICTCLAS.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.radioButton_tokLib_ICTCLAS.setChecked(False)
        self.radioButton_tokLib_ICTCLAS.setObjectName("radioButton_tokLib_ICTCLAS")
        self.radioButton_tokLib_Jieba = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_tokLib_Jieba.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.radioButton_tokLib_Jieba.setChecked(False)
        self.radioButton_tokLib_Jieba.setObjectName("radioButton_tokLib_Jieba")
        self.radioButton_tokLib_spaCy = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_tokLib_spaCy.setGeometry(QtCore.QRect(10, 80, 111, 17))
        self.radioButton_tokLib_spaCy.setChecked(False)
        self.radioButton_tokLib_spaCy.setObjectName("radioButton_tokLib_spaCy")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(9, 50, 141, 20))
        self.label_4.setObjectName("label_4")
        self.myTextInput_Convert_fileOut = QtWidgets.QLineEdit(self.tab_2)
        self.myTextInput_Convert_fileOut.setGeometry(QtCore.QRect(9, 70, 341, 21))
        self.myTextInput_Convert_fileOut.setObjectName("myTextInput_Convert_fileOut")
        self.toolButton_Convert = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_Convert.setGeometry(QtCore.QRect(360, 30, 23, 18))
        self.toolButton_Convert.setObjectName("toolButton_Convert")
        self.myTextInput_Convert_fileIn = QtWidgets.QLineEdit(self.tab_2)
        self.myTextInput_Convert_fileIn.setGeometry(QtCore.QRect(10, 30, 341, 21))
        self.myTextInput_Convert_fileIn.setObjectName("myTextInput_Convert_fileIn")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 211, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radioButton_zht2zhs = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_zht2zhs.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.radioButton_zht2zhs.setChecked(True)
        self.radioButton_zht2zhs.setObjectName("radioButton_zht2zhs")
        self.radioButton_zhs2zht = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_zhs2zht.setGeometry(QtCore.QRect(10, 30, 181, 17))
        self.radioButton_zhs2zht.setChecked(False)
        self.radioButton_zhs2zht.setObjectName("radioButton_zhs2zht")
        self.radioButton_enLowercse = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_enLowercse.setGeometry(QtCore.QRect(10, 50, 181, 17))
        self.radioButton_enLowercse.setObjectName("radioButton_enLowercse")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_Convert = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Convert.setGeometry(QtCore.QRect(260, 100, 91, 21))
        self.pushButton_Convert.setObjectName("pushButton_Convert")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.TextInput_lib = QtWidgets.QLineEdit(self.tab)
        self.TextInput_lib.setGeometry(QtCore.QRect(10, 30, 271, 21))
        self.TextInput_lib.setObjectName("TextInput_lib")
        self.toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.toolButton_2.setGeometry(QtCore.QRect(290, 30, 23, 18))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 201, 20))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.label_8.setObjectName("label_8")
        self.TextInput_lib_2 = QtWidgets.QLineEdit(self.tab)
        self.TextInput_lib_2.setGeometry(QtCore.QRect(10, 80, 271, 21))
        self.TextInput_lib_2.setText("")
        self.TextInput_lib_2.setObjectName("TextInput_lib_2")
        self.pushButton_Segment_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Segment_2.setGeometry(QtCore.QRect(320, 180, 101, 21))
        self.pushButton_Segment_2.setObjectName("pushButton_Segment_2")
        self.tabWidget.addTab(self.tab, "")
        self.label = QtWidgets.QLabel(SegPoi)
        self.label.setGeometry(QtCore.QRect(20, 10, 591, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(SegPoi)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 61, 16))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(SegPoi)
        self.textBrowser.setGeometry(QtCore.QRect(20, 310, 331, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(SegPoi)
        self.progressBar.setGeometry(QtCore.QRect(20, 390, 361, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(SegPoi)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SegPoi.accept)
        self.buttonBox.rejected.connect(SegPoi.reject)
        QtCore.QMetaObject.connectSlotsByName(SegPoi)

    def retranslateUi(self, SegPoi):
        _translate = QtCore.QCoreApplication.translate
        SegPoi.setWindowTitle(_translate("SegPoi", "SegPoi"))
        self.tabWidget.setToolTip(_translate("SegPoi", "<html><head/><body><p>Chinese word segmentation (or tokenization)</p></body></html>"))
        self.checkBox_POS.setText(_translate("SegPoi", "詞性標記 POS"))
        self.label_2.setText(_translate("SegPoi", "輸出檔 Output file name"))
        self.pushButton_Segment.setText(_translate("SegPoi", "進行分詞 Tokenize"))
        self.myTextInput_2.setText(_translate("SegPoi", "C:/CAT/Data/oldc4.zht.seg.txt"))
        self.toolButton.setText(_translate("SegPoi", "..."))
        self.radioButton_zht.setText(_translate("SegPoi", "正體中文 Traditional Chinese"))
        self.radioButton_zhs.setText(_translate("SegPoi", "簡體中文 Simplified Chinese"))
        self.radioButton_en.setText(_translate("SegPoi", "English"))
        self.myTextInput.setText(_translate("SegPoi", "C:/CAT/Data/oldc4.zht.txt"))
        self.pushButton_Check.setText(_translate("SegPoi", "Check Parameters"))
        self.groupBox.setTitle(_translate("SegPoi", "分詞套件 Tokenization library"))
        self.radioButton_tokLib_Stanford.setText(_translate("SegPoi", "Stanford CoreNLP"))
        self.radioButton_tokLib_ICTCLAS.setText(_translate("SegPoi", "ICTCLAS/NLPIR"))
        self.radioButton_tokLib_Jieba.setText(_translate("SegPoi", "Jieba"))
        self.radioButton_tokLib_spaCy.setText(_translate("SegPoi", "spaCy (English only)"))
        self.label_6.setText(_translate("SegPoi", "請選擇輸入檔 Select input file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SegPoi", "中文分詞"))
        self.label_4.setText(_translate("SegPoi", "輸出檔 Output file name"))
        self.myTextInput_Convert_fileOut.setText(_translate("SegPoi", "C:/NLP/collo/chinatimes2014.zhs.txt"))
        self.toolButton_Convert.setText(_translate("SegPoi", "..."))
        self.myTextInput_Convert_fileIn.setText(_translate("SegPoi", "C:/NLP/collo/chinatimes2014.txt"))
        self.radioButton_zht2zhs.setText(_translate("SegPoi", "正體轉簡體 Traditional -> Simplified"))
        self.radioButton_zhs2zht.setText(_translate("SegPoi", "簡體轉正體 Simplified -> Traditional"))
        self.radioButton_enLowercse.setText(_translate("SegPoi", "English (convert to all lowercase)"))
        self.label_7.setText(_translate("SegPoi", "請選擇輸入檔 Select input file"))
        self.pushButton_Convert.setText(_translate("SegPoi", "轉換 Convert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SegPoi", "正體/簡體轉換"))
        self.TextInput_lib.setText(_translate("SegPoi", "C:/CAT/StanfordCoreNLP/"))
        self.toolButton_2.setText(_translate("SegPoi", "..."))
        self.label_5.setText(_translate("SegPoi", "Stanford CoreNLP Library location"))
        self.label_8.setText(_translate("SegPoi", "User dictionary (ICTCLAS/NLPIR)"))
        self.pushButton_Segment_2.setText(_translate("SegPoi", "儲存設定 Save Profile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SegPoi", "系統參數設定 Configuration"))
        self.label.setText(_translate("SegPoi", "<html><head/><body><p><span style=\" font-size:12pt; color:#aa0000;\">中英文文檔處理介面 Chinese/English text processing interface 2</span></p></body></html>"))
        self.label_3.setText(_translate("SegPoi", "Messages"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SegPoi = QtWidgets.QDialog()
    ui = Ui_SegPoi()
    ui.setupUi(SegPoi)
    SegPoi.show()
    sys.exit(app.exec_())

